Adding community profile: leighphan.md
fullstackla/pairing-meetup pull request #104
Opened 2016-10-20 02:53 UTC by leighphan

2016-10-20 03:01 UTC, gr2m requested changes

2016-10-20 03:01 UTC, gr2m commented on community/leighphan.md
> +- Website: [hello](http://leighphan.github.io/hello)
I think you can just set the URLs instead of using the markdown syntax, it will be easier to parse later with JavaScript

2016-10-21 03:29 UTC, leighphan commented on community/leighphan.md
> +- Website: [hello](http://leighphan.github.io/hello)
Good catch; I've removed the markdown formatting.

2016-10-21 04:21 UTC, gr2m approved these changes
👌

2016-10-21 04:21 UTC, merged

2016-10-21 06:26 UTC, machikoyasuda commented
![corgi-treadmill](https://cloud.githubusercontent.com/assets/3673236/19588743/9f61d8b2-971c-11e6-860c-e8f8c7da4f36.gif)
For Cory <3